pipeline {
    agent {
        label 'AGENT-1'
    }
    environment {
        appVersion = ''
        region = 'us-east-1'
        account_id = '143094436925'
        project = 'roboshop'
    }
    stages {
        stage('terraform init') {
            steps {
                script {
                    
                  withAWS(credentials: 'aws-auth', region: 'us-east-1') {
                    sh """ 
                         cd 00-vpc
                         terraform init -reconfigure
                    """ }
                
                }
            
            
            
            }
        
        
        
        }
       }
    

}