pipeline {
    agent {
        label 'AGENT-1'
    }
    environment {
        appVersion = ''
        region = 'us-east-1'
        account_id = '143094436925'
        project = 'roboshop'
    }
    options {
        timeout(time:30, unit:'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    stages {
        stage('terraform init') {
            steps {
                script {
                    
                  withAWS(credentials: 'aws-auth', region: 'us-east-1') {
                    sh """ 
                         cd 10-sg
                         terraform init -reconfigure
                    """ }
                
                }
            
            }
        
        }

        stage('terraform plan') {
            steps {
                script {
                    
                  withAWS(credentials: 'aws-auth', region: 'us-east-1') {
                    sh """ 
                         cd 10-sg
                         terraform plan
                    """ }
                
                }
            
            }
        
        }
        stage('terraform apply') {
            steps {
                script {
                    
                  withAWS(credentials: 'aws-auth', region: 'us-east-1') {
                    sh """ 
                         cd 10-sg
                         terraform apply -auto-approve
                    """ }
                
                }
            
            }
        
        }

    }
    

}